export const VIBE_CATEGORIES = {
  COZY_INTIMATE: {
    label: "Cozy & Intimate",
    description: "Warm, quiet, romantic — built for real conversation",
    accent: "#b45309",
    bgClass: "bg-amber-50 border-amber-200",
    badgeClass: "bg-amber-50 text-amber-800 border-amber-200",
    iconBg: "bg-amber-100",
    mapColor: "#d97706",
  },
  LIVELY_ENERGETIC: {
    label: "Lively & Energetic",
    description: "Buzzing room, social scene, the energy doesn't quit",
    accent: "#ca8a04",
    bgClass: "bg-yellow-50 border-yellow-200",
    badgeClass: "bg-yellow-50 text-yellow-800 border-yellow-200",
    iconBg: "bg-yellow-100",
    mapColor: "#eab308",
  },
  UPSCALE_REFINED: {
    label: "Upscale & Refined",
    description: "Fine dining, exceptional service, special-occasion worthy",
    accent: "#7c3aed",
    bgClass: "bg-violet-50 border-violet-200",
    badgeClass: "bg-violet-50 text-violet-800 border-violet-200",
    iconBg: "bg-violet-100",
    mapColor: "#8b5cf6",
  },
  CASUAL_CHILL: {
    label: "Casual & Chill",
    description: "Relaxed, unpretentious, no dress code required",
    accent: "#16a34a",
    bgClass: "bg-green-50 border-green-200",
    badgeClass: "bg-green-50 text-green-800 border-green-200",
    iconBg: "bg-green-100",
    mapColor: "#22c55e",
  },
  TRENDY_HIPSTER: {
    label: "Trendy & Artsy",
    description: "Curated, creative, the scene everyone wants to be in",
    accent: "#db2777",
    bgClass: "bg-pink-50 border-pink-200",
    badgeClass: "bg-pink-50 text-pink-800 border-pink-200",
    iconBg: "bg-pink-100",
    mapColor: "#ec4899",
  },
  FAMILY_FRIENDLY: {
    label: "Family Friendly",
    description: "Welcoming to all ages, comfortable and unpretentious",
    accent: "#2563eb",
    bgClass: "bg-blue-50 border-blue-200",
    badgeClass: "bg-blue-50 text-blue-800 border-blue-200",
    iconBg: "bg-blue-100",
    mapColor: "#3b82f6",
  },
  SPORTS_BAR: {
    label: "Sports Bar",
    description: "Screens everywhere, game-day crowd, cold drafts",
    accent: "#ea580c",
    bgClass: "bg-orange-50 border-orange-200",
    badgeClass: "bg-orange-50 text-orange-800 border-orange-200",
    iconBg: "bg-orange-100",
    mapColor: "#f97316",
  },
  DIVE_BAR: {
    label: "Dive Bar",
    description: "No-frills, character-rich, authentically local",
    accent: "#57534e",
    bgClass: "bg-stone-50 border-stone-200",
    badgeClass: "bg-stone-50 text-stone-700 border-stone-200",
    iconBg: "bg-stone-100",
    mapColor: "#78716c",
  },
  ROOFTOP_VIEWS: {
    label: "Rooftop Views",
    description: "Outdoor setting, skyline backdrop, drinks with altitude",
    accent: "#0284c7",
    bgClass: "bg-sky-50 border-sky-200",
    badgeClass: "bg-sky-50 text-sky-800 border-sky-200",
    iconBg: "bg-sky-100",
    mapColor: "#0ea5e9",
  },
  HIDDEN_GEM: {
    label: "Hidden Gem",
    description: "Under the radar, worth hunting down, locals only",
    accent: "#0f766e",
    bgClass: "bg-teal-50 border-teal-200",
    badgeClass: "bg-teal-50 text-teal-800 border-teal-200",
    iconBg: "bg-teal-100",
    mapColor: "#14b8a6",
  },
} as const;

export type VibeCategoryKey = keyof typeof VIBE_CATEGORIES;

export function getVibeCategory(key: string) {
  return VIBE_CATEGORIES[key as VibeCategoryKey] ?? null;
}
